[project]
name = "etabsmodeling"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "comtypes<=1.4.12",
    "ezdxf>=1.4.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
]
